todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ToDo/', include('todo_tasks.urls', namespace="todoList"))
]

todo_tasks/urls.py
from django.urls import path
from . import views

app_name = 'todoList'

urlpatterns = [
    path("", views.home, name="home-page"),
    path("list/<int:user_id>", views.ToDoListView, name="todo-list"),
    path("delete-task/<int:task_id>/<int:user_id>", views.DeleteTask, name="delete-task"),
    path("update-task/<int:task_id>/<int:user_id>", views.UpdateTask, name="update-task"),

    path("signup/", views.SignUpView, name="sign-up"),
    path("login/", views.LoginView, name="log-in"),
    path("logout/", views.LogoutView, name="log-out"),

]

todo_tasks/models.py
from django.db import models

# Create your models here.
class userModel(models.Model):
    username = models.CharField(max_length=50)
    email = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.username


class ToDoModel(models.Model):
    User = models.ForeignKey(userModel, on_delete=models.CASCADE, blank=True, null=True)
    task = models.CharField(max_length=500, blank=False)
    created = models.DateTimeField(auto_now=True)
    order = models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.task

todo_tasks/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class ToDoForm(forms.Form):
    task = forms.CharField(label="Task", max_length=500)


class SignUpForm(forms.ModelForm):
    password = forms.CharField(label="Set-Password", widget=forms.PasswordInput)
    confirmpassword = forms.CharField(label="Confirm-Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_confirmpassword(self):
        cd = self.cleaned_data

        if cd['password'] != cd['confirmpassword']:
            raise ValidationError("Your password does not match, please re-enter password again")
        
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

todo_tasks/views.py
from django.shortcuts import render, redirect
from django.http import request
from django.contrib.auth import authenticate, login, logout
from .forms import ToDoForm, SignUpForm, LoginForm
from .models import ToDoModel, userModel

def home(request):
    return render(request, 'base.html')

def SignUpView(request):
    if request.method == "POST":
        signupForm = SignUpForm(request.POST)
        if signupForm.is_valid():
            user = signupForm.save(commit=False)
            user.set_password(signupForm.cleaned_data['password'])
            user.save()

            userModel.objects.create(username=signupForm.cleaned_data['username'], email=signupForm.cleaned_data['email'])
            return redirect('todoList:log-in')
    else:
        signupForm = SignUpForm()

    return render(request, 'authenticate/signup.html', {'form': signupForm, 'user':''})

def LoginView(request):
    if request.method == "POST":
        loginForm = LoginForm(request.POST)
        if loginForm.is_valid():
            cd = loginForm.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user:
                login(request, user)

                # get loggedin user
                current_user = userModel.objects.filter(email=user.email).values_list("id", flat=True)[0]
                print(current_user)
                return redirect('todoList:todo-list', user_id=current_user)
                # return render(request, 'ToDoList.html', {'user': user})
            else:
                return render(request, 'base.html', {'error_msg': "Invalid credentials, please provide valid credentials for login"})
    else:
        loginForm = LoginForm()
    return render(request, 'authenticate/login.html', {'form': loginForm, 'user': ''})

def LogoutView(request):
    logout(request)
    return render(request, 'base.html', {'user': ''})

def ToDoListView(request, user_id):
    print("ToDoList User_id", user_id)
    user = userModel.objects.get(pk=user_id)
    all_tasks = ToDoModel.objects.filter(User=user)
    if request.method == "POST":
        task_form = ToDoForm(request.POST)
        if task_form.is_valid():
            task = task_form.cleaned_data

            tasks_count = ToDoModel.objects.filter(User=user_id).count()

            
            ToDoModel.objects.create(User=user, task=task['task'], order=tasks_count+1)

            task_form = ToDoForm()
    else:
        task_form = ToDoForm()
    
    return render(request, 'ToDoList.html', {'task_form': task_form, 'tasks': all_tasks})

def DeleteTask(request, task_id, user_id):
    print("Delete task: ", user_id)
    user = userModel.objects.get(pk=user_id)
    task_to_delete = ToDoModel.objects.get(pk=task_id)
    task_to_delete.delete()

    # reorder tasks on deleting a specific task
    tasks = ToDoModel.objects.filter(User=user)
    prev_order = 0
    tasks_count = tasks.count()
    for task in range(0, tasks_count):
        taskObj = tasks[task]
        if task == 0:
            if taskObj.order != 1:
                taskObj.order = 1
        else:
            if taskObj.order != prev_order+1:
                taskObj.order = prev_order+1
        prev_order = taskObj.order
        print("order:", taskObj.order)
        taskObj.save()

    return redirect("todoList:todo-list", user_id=user_id)

def UpdateTask(request, task_id, user_id):
    instance = ToDoModel.objects.get(pk=task_id)
    user = userModel.objects.get(pk=user_id)

    if request.method == 'POST':
        task_form = ToDoForm(request.POST)
        if task_form.is_valid():
            task = task_form.cleaned_data
            print(task['task'])
            instance.task = task['task']
            instance.save()
            all_tasks = ToDoModel.objects.filter(User = user)
            return redirect("todoList:todo-list", user_id=user_id)

    else:
        data = {
            'task': instance.task
        }
        task_form = ToDoForm(initial=data)
        all_tasks = ToDoModel.objects.filter(User=user)

    return render(request, 'update.html', {'task_form': task_form, 'tasks': all_tasks,
                                           'instance': instance.id}) 

todo_tasks/templates/ToDoList.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% for field in task_form %}
            {{field.label_tag}} {{field}}
        {% endfor %}
        <input type="submit" name="Add Task" class="AddButton">
        {% csrf_token %}
    </form>

    {% if tasks %}
        <table class="tasksTable">
            <tr> 
                <th> S.no </th>
                <th> Task </th>
                <th> Actions </th>
            </tr>
            {% for task in tasks %}
            <tr>
                <td> {{task.order}} </td>
                <td id="task"> {{task.task}} <br>
                    <hr> </hr>
                     <p> <em> {{task.created}}</em> </p>
                </td>
                <td id="taskAction">
                    <a href="{% url 'todoList:update-task' task.id task.User.id %}" class="update-button"> Update </a>
                    
                    <a href="{% url 'todoList:delete-task' task.id task.User.id %}" class="delete-button"> Delete </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <li> No tasks, Please add your task </li>
    {% endif %}
{% endblock %}

todo_tasks/templates/authenticate/login.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% for field in form %}
            {{field.label_tag}} <br>
            {{field}} <br>
        {% endfor %}
        {% csrf_token %}
        <input type="submit" name="Login">
    </form>
{% endblock %}

todo_tasks/templates/authenticate/signup.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% for field in form %}
            {{field.label_tag}} <br>
            {{field}} <br>
        {% endfor %}
        {% csrf_token %}
        <input type="submit" name="SignUp">
    </form>
{% endblock %}

todo_tasks/templates/base.html
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> To Do </title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">ToDo List</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="">Home</a>
                  </li>
                </ul>
                <span class="navbar-text">
                  <ul class="navbar-nav">
                    {% if user %}
                        <li class="nav-item">
                            Welcome: {{user}}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'todoList:log-out' %}"> Logout </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'todoList:log-in' %}"> Login </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'todoList:sign-up' %}"> Signup </a>
                        </li>
                    {% endif %}
                  </ul>
                </span>
              </div>
            </div>
          </nav>
        
        <h3> Welcome to your To-Do List </h3>

        {% if error_msg %}
        <div>
            <li> {{error_msg}} </li>
        </div>
        {% endif %}

        <div class="container">
            {% block content %}

            {% endblock %}
        </div>
    </body>
</html>

todo_tasks/templates/update.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% for field in task_form %}
            {{field.label_tag}} {{field}}
        {% endfor %}
        <input type="submit" name="Add Task" class="AddButton">
        {% csrf_token %}
    </form>


    {% if tasks %}
        <table class="tasksTable">
            <tr> 
                <th> S.no </th>
                <th> Task </th>
                <th> Actions </th>
            </tr>
            {% for task in tasks %}
            <tr {% if task.id == instance %} class="selected" {% endif %}>
                <td> {{task.order}} </td>
                <td id="task"> {{task.task}} <br>
                    <hr> </hr>
                     <p> <em> {{task.created}}</em> </p>
                </td>
                <td id="taskAction">
                    <a href="{% url 'todoList:update-task' task.id task.User.id%}" class="update-button"> Update </a>
                    
                    <a href="{% url 'todoList:delete-task' task.id task.User.id %}" class="delete-button"> Delete </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <li> No tasks, Please add your task </li>
    {% endif %}
{% endblock %}